name: draco build

permissions:
  contents: read

on:
  push:
    branches:
      - 'main'
    paths:
      - '**/draco.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
  
    steps:
      - uses: actions/checkout@v7
        with:
          repository: 0xchasercat/draco

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: 构建 Release 版本
        run: |
          rustc --version --verbose
          cargo --version --verbose
          cargo build --locked --release --verbose --package draco-cli
          
      - uses: actions/upload-artifact@v7
        name: Upload the artifact
        with:
          name: ${{ matrix.os }}-binary
          path: target/release/draco
